"""init schema clean

Revision ID: 4125d212c4aa
Revises:
Create Date: 2026-10-04 20:36:58.955673

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4125d212c4aa"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("interval", sa.String(), nullable=False),
        sa.Column("open_time", sa.BigInteger(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol", "interval", "open_time", name="uq_candles_symbol_interval_open_time"
        ),
    )
    op.create_index(op.f("ix_candles_id"), "candles", ["id"], unique=False)
    op.create_index(op.f("ix_candles_interval"), "candles", ["interval"], unique=False)
    op.create_index(op.f("ix_candles_open_time"), "candles", ["open_time"], unique=False)
    op.create_index(op.f("ix_candles_symbol"), "candles", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_candles_symbol"), table_name="candles")
    op.drop_index(op.f("ix_candles_open_time"), table_name="candles")
    op.drop_index(op.f("ix_candles_interval"), table_name="candles")
    op.drop_index(op.f("ix_candles_id"), table_name="candles")
    op.drop_table("candles")
    # ### end Alembic commands ###
